name: build
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          ./docker-prep.sh
          make test
          export APNIC_RANDOMISE_ZERO=1
          make test
