name: build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo apt-get update && sudo apt-get install gcc build-essential cpanminus cmake git libssh-dev rustc cargo golang
          cargo install rtrtr
          export PATH=$PATH:/root/.cargo/bin
          git clone https://github.com/bgp/stayrtr
          cd stayrtr
          go install cmd/stayrtr/stayrtr.go
          export PATH=$PATH:/root/go/bin
          git clone https://github.com/tanneberger/rtrlib
          cd rtrlib
          git checkout aspa-fixes
          sed -i 's/case EOD:/case EOD:\n;/' rtrlib/rtr/packets.c
          rm doxygen/examples/rtr_mgr.c
          cat doxygen/examples/CMakeLists.txt | grep -v rtr_mgr > asdf; mv asdf doxygen/examples/CMakeLists.txt
          cmake -D CMAKE_BUILD_TYPE=Debug . && make && sudo make install
          cd .. && rm -rf rtrlib
          export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
          sudo ldconfig
          sudo cpanm . && sudo make clean
          export HAS_RTRCLIENT=1
          export HAS_ASPA_RTRCLIENT=1
          export HAS_RTRTR=1
          export HAS_STAYRTR=1
          export APNIC_DEBUG=1
          perl Makefile.PL && make && make test
