name: build
on: push
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          ./docker-prep.sh
          ./docker-mkcert.sh
          ./docker-rtrlib.sh
          export HAS_RTRCLIENT=1
          export HAS_ASPA_RTRCLIENT=1
          export HAS_RTRTR=1
          export HAS_STAYRTR=1
          export APNIC_DEBUG=1
          export PATH=$PATH:/root/.cargo/bin
          sudo cpanm -v --installdeps .
          sudo make clean || true
          perl Makefile.PL && make && make test
          export APNIC_RANDOMISE_ZERO=1
          make test
