name: build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo apt-get update && sudo apt-get install build-essential cpanminus cmake git libssh-dev
          git clone https://github.com/tanneberger/rtrlib
          cd rtrlib
          cmake -D CMAKE_BUILD_TYPE=Debug . && make && sudo make install
          cd .. && rm -rf rtrlib
          sudo cpanm . && sudo make clean
          export HAS_RTRCLIENT=1
          export HAS_ASPA_RTRCLIENT=1
          export APNIC_DEBUG=1
          perl Makefile.PL && make && make test
